// Package gcode can write gcode files.
// This is a text-based format that is used to control
// CNC machines and XY-plotters.
package gcode

import (
	"bufio"
	"fmt"
	"io"
)

// Config provides options to write a gcode file.
type Config struct {
	PenUp    int
	FeedRate int
}

// A Writer is can write gcode files.
// Errors during writing are held, and not reported until the final
// Flush() call.
//
// After construction, the writer should be used like this:
//   w.Preamble()
//   some w.Move(...) and w.Line(...) commands
//   w.Postamble()
//   if err := w.Flush(); err != nil {
//      .. handle error
//   }
type Writer struct {
	err error
	w   *bufio.Writer
	cfg *Config
}

// NewWriter creates a new gcode writer.
func NewWriter(w io.Writer, cfg *Config) *Writer {
	return &Writer{
		w:   bufio.NewWriter(w),
		cfg: cfg,
	}
}

func (w *Writer) outf(x string, args ...interface{}) {
	if w.err != nil {
		return
	}
	_, w.err = fmt.Fprintf(w.w, x+"\n", args...)
}

// Preamble writes the intial part of a gcode file.
func (w *Writer) Preamble() {
	w.outf("(generated by svgtocode, (c) Paul Hankin 2020)")
	w.outf("M3S%d (pen up)", w.cfg.PenUp)
	w.outf("G21 (use mm)")
	w.outf("G90 (use absolute coords)")
	w.outf("G1F%d (g1 feed rate %dmm/min)", w.cfg.FeedRate, w.cfg.FeedRate)
}

// Postamble writes the final part of a gcode file.
func (w *Writer) Postamble() {
	w.outf("M3S50 (pen up)")
	w.outf("G0 X0Y0 (home)")
}

// Move writes a command that moves the pen to the given location.
// The pen goes down after this move, so the next command should be a line.
func (w *Writer) Move(x, y float64) {
	w.outf("M3\nG4 P0.1\nG0 X%.3f Y%.3f\nM5\nG4 P0.1", x, y)
}

// Line moves the downed pen to the given location.
func (w *Writer) Line(x, y float64) {
	w.outf("G1 X%.3f Y%.3f", x, y)
}

// Flush flushes any unwritten data to the file, and returns
// any error that may have occurred during the time the gcode
// file was being written.
func (w *Writer) Flush() error {
	if w.err != nil {
		return w.err
	}
	if err := w.w.Flush(); err != nil {
		return err
	}
	return nil
}
